export const TIPO_OS_OPTIONS = ['PREVENTIVA', 'CORRETIVA', 'REVISAO', 'SINISTRO'] as const;
export const STATUS_OS_OPTIONS = ['ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'ATRASADA', 'CANCELADA'] as const;
export const PRIORIDADE_OS_OPTIONS = ['BAIXA', 'MEDIA', 'ALTA'] as const;
